'use strict';
(async()=>{
const STORAGE_KEY='italoluc-projects-draft-v1';
const form=document.querySelector('#project-form'), notice=document.querySelector('#notice'), errorBox=document.querySelector('#form-error');
let projects=await ProjectStore.loadPublished(), selected=null, dirty=false;
try { const saved=localStorage.getItem(STORAGE_KEY); if(saved){projects=ProjectStore.parse(saved);notice.textContent='Rascunho local recuperado. O site publicado continua usando o arquivo do GitHub.';} } catch{notice.textContent='Não foi possível recuperar o rascunho. Usando os dados publicados.';}
function make(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;}
function saveDraft(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(projects));document.querySelector('#draft-state').textContent='RASCUNHO SALVO NESTE NAVEGADOR';}catch{document.querySelector('#draft-state').textContent='RASCUNHO APENAS NESTA ABA';notice.textContent='O navegador não conseguiu guardar o rascunho. Exporte agora para não perder os dados.';}}
function leaveForm(){return !dirty || confirm('Há alterações no formulário que ainda não foram salvas. Descartar essas alterações?');}
function renderList(){
 document.querySelector('#count').textContent=projects.length;const list=document.querySelector('#items');list.replaceChildren();
 if(!projects.length)list.append(make('p','empty-list','Nenhum projeto cadastrado. Clique em + Novo para começar.'));
 projects.forEach((p,index)=>{const item=make('div','project-item'+(selected===p.id?' active':''));const edit=make('button','item-select',p.title);edit.type='button';edit.addEventListener('click',()=>{if(leaveForm())select(p.id);});item.append(edit,make('span','small-label',String(index+1).padStart(2,'0')+' / '+{live:'NO AR',development:'EM DESENVOLVIMENTO',experiment:'EXPERIMENTO'}[p.status]));const actions=make('div','item-controls');for(const [symbol,delta,label] of [['↑',-1,'Mover para cima'],['↓',1,'Mover para baixo']]){const b=make('button','',symbol);b.type='button';b.setAttribute('aria-label',label+': '+p.title);b.disabled=index+delta<0||index+delta>=projects.length;b.addEventListener('click',()=>{[projects[index],projects[index+delta]]=[projects[index+delta],projects[index]];saveDraft();renderList();});actions.append(b);}const del=make('button','','Excluir');del.type='button';del.setAttribute('aria-label','Excluir: '+p.title);del.addEventListener('click',()=>{if(!confirm('Excluir '+p.title+' do rascunho?'))return;projects=projects.filter(x=>x.id!==p.id);if(selected===p.id)select(null);saveDraft();renderList();notice.textContent='Projeto removido do rascunho. A exclusão só aparece no site após publicar o arquivo.';});actions.append(del);item.append(actions);list.append(item);});
}
function select(id){selected=id;form.reset();document.querySelector('#image-file').value='';errorBox.textContent='';const p=projects.find(x=>x.id===id);if(p)for(const key of ['id','title','description','descriptionEn','url','status','image'])form.elements[key].value=p[key];if(p)form.elements.tags.value=p.tags.join(', ');document.querySelector('#form-mode').textContent=p?'EDITANDO / '+p.title:'NOVO PROJETO';dirty=false;renderList();preview();}
function values(){return {id:selected||('project-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)),title:form.elements.title.value,description:form.elements.description.value,descriptionEn:form.elements.descriptionEn.value,url:form.elements.url.value,tags:form.elements.tags.value.split(',').map(t=>t.trim()).filter(Boolean),status:form.elements.status.value,image:form.elements.image.value};}
function preview(){const p=values(), box=document.querySelector('#card-preview');box.replaceChildren();const card=make('div','preview-card');const image=ProjectStore.safeUrl(p.image,true);if(image){const img=make('img');img.src=image;img.alt=p.title;img.addEventListener('error',()=>img.remove(),{once:true});card.append(img);}card.append(make('h3','',p.title||'Nome do projeto'),make('p','',p.description||'A descrição do projeto aparece aqui.'));const tags=make('div','tags');p.tags.slice(0,15).forEach(t=>tags.append(make('span','',t)));card.append(tags);const url=ProjectStore.safeUrl(p.url);if(url){const a=make('a','','Conhecer projeto ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}box.append(card);}
form.addEventListener('input',()=>{dirty=true;preview();});form.addEventListener('change',()=>{dirty=true;preview();});
form.addEventListener('submit',e=>{e.preventDefault();try{const p=ProjectStore.validate([values()])[0];const index=projects.findIndex(x=>x.id===p.id);if(index>=0)projects[index]=p;else projects.push(p);select(p.id);saveDraft();notice.textContent='Projeto salvo no rascunho. Exporte e atualize data/projects.js para publicar.';}catch(error){errorBox.textContent=error.message;}});
document.querySelector('#new').addEventListener('click',()=>{if(leaveForm()){select(null);form.elements.title.focus();}});
document.querySelector('#clear-image').addEventListener('click',()=>{form.elements.image.value='';document.querySelector('#image-file').value='';dirty=true;preview();});
document.querySelector('#image-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1048576){errorBox.textContent='Escolha um PNG, JPEG ou WebP com até 1 MB.';e.target.value='';return;}try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});form.elements.image.value=data;dirty=true;errorBox.textContent='';preview();}catch{errorBox.textContent='Não foi possível carregar a imagem.';}});
document.querySelector('#export').addEventListener('click',()=>{if(dirty){notice.textContent='Salve as alterações do formulário antes de exportar.';form.querySelector('button[type="submit"]').focus();return;}try{const url=URL.createObjectURL(new Blob([ProjectStore.serialize(projects)],{type:'text/javascript;charset=utf-8'}));const a=make('a');a.href=url;a.download='projects.js';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notice.textContent='Arquivo exportado. Substitua data/projects.js no GitHub e confirme o commit para publicar.';}catch(error){notice.textContent=error.message;}});
document.querySelector('#import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>12000000)throw Error('Arquivo muito grande.');const next=ProjectStore.parse(await file.text());if(!leaveForm())return;if(!confirm('Substituir o rascunho atual pelos '+next.length+' projetos deste arquivo?'))return;projects=next;select(projects[0]?.id||null);saveDraft();notice.textContent='Arquivo importado para o rascunho. Nenhuma alteração foi publicada.';}catch(error){notice.textContent='Não foi possível importar: '+error.message;}finally{e.target.value='';}});
document.querySelector('#restore').addEventListener('click',()=>{if(!leaveForm()||!confirm('Descartar o rascunho e restaurar os projetos do arquivo publicado?'))return;projects=ProjectStore.validate(window.PORTFOLIO_PROJECTS);select(projects[0]?.id||null);saveDraft();notice.textContent='Rascunho restaurado com os dados publicados carregados nesta página.';});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
select(projects[0]?.id||null);saveDraft();

})();
